# -*- coding: utf-8 -*-
{
    "name": "Buynow Shang Yi",
    "author": "kimweng",
    "version": "2.0",
    "depends": ['product', 'base', 'stock', 'hr', 'account', 'sale', 'mail'],
    "description": """Shang Yi""",
    "init_xml": [],
    "data": [
             'views/sy_product.xml',
             'views/sy_pos_order.xml',
             'views/sy_pos_payment.xml',
             'views/sy_pos_order_report.xml',
             'views/product_brand.xml',
             'views/sale_plan.xml',
             'views/brand_plan_report.xml',
             'views/check_account.xml',
             'views/product_template.xml',
             'views/deduct_fund.xml',
             'views/ortherdetain.xml',
             'views/deduct_fund_change.xml',
             'views/ir_sequence.xml',
             'views/check_list_product.xml',
             'views/receipt.xml',
             'views/import_list_product.xml',
             'views/import_sale_plan.xml',
             'views/mail_mail.xml',
             'views/res_users.xml',
#             'views/stock_check.xml',
             'views/sale_plan_model.xml',
             'views/compute_rate.xml',
             'report/print_check_account.xml',
             'report/print_view.xml',
            'views/sync_shangyi_data.xml',
             'menu.xml',
             'security/bn_shangyi.xml',
             'security/ir.model.access.csv',
             ],
    "installable": True,
    "auto_install": False,
}
